### ISSUE TITLE
Группировка Пулл реквестов

### ISSUE THREAD

**Issue by sergeyvlakh** [Tehtehteh/ghook_v2#10]
На данный момент, сообщение в слак идёт в формате:
`"@Username, please check PR: %github_link%"`.
Нужна более детальная информация по пулл реквесту: автор, название, проект (хоть он и виден в линке, всё равно, желательно его дублировать ради читаемости сообщений"

**Comment by Tehtehteh** [comment]
Реализовано в ветке `refactor/request-adapter`
